apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  labels:
    kubesphere.io/cluster: host
    kubesphere.io/namespace: pgo
  name: postgre-2233
  namespace: pgo
spec:
  appVersion: '1.1.0 [15.6]'
  customResource: >-
    {"apiVersion":"pgcluster.kubesphere.io/v1alpha1","kind":"PostgreSQLCluster","metadata":{"name":"postgre-2233","namespace":"pgo"},"spec":{"name":"postgre-g19yu8","namespace":"pgo","syncReplication":true,"ccpImage":"","ccpImageTag":"","replicaCount":1,"cpuLimit":"500m","cpuRequest":"500m","memoryLimit":"1Gi","memoryRequest":"1Gi","database":"postgreSQL","username":"kubsphere","password":"Ks2020!","restart":false,"storageConfig":"csi-super-high-perf","replicaName":"","managedUser":true,"showSystemAccounts":true,"setSystemAccountPassword":false,"pvcSize":"10Gi"}}
  kind: PostgreSQLCluster
  version: 1