apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-pg-delete-user
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      # delete user
      action: "delete_user"
      clientVersion: "4.7.1"
      namespace: "pgtest"
      clusterName:
        - "test001"
      allFlag: false
      username: "mgw"
      selector: ""