/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	applicationv1alpha1 "github.com/manifest/api/application/v1alpha1"
	versioned "github.com/manifest/pkg/client/clientset/versioned"
	internalinterfaces "github.com/manifest/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/manifest/pkg/client/listers/application/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// OperatorApplicationVersionInformer provides access to a shared informer and lister for
// OperatorApplicationVersions.
type OperatorApplicationVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.OperatorApplicationVersionLister
}

type operatorApplicationVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewOperatorApplicationVersionInformer constructs a new informer for OperatorApplicationVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOperatorApplicationVersionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOperatorApplicationVersionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredOperatorApplicationVersionInformer constructs a new informer for OperatorApplicationVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOperatorApplicationVersionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApplicationV1alpha1().OperatorApplicationVersions().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApplicationV1alpha1().OperatorApplicationVersions().Watch(context.TODO(), options)
			},
		},
		&applicationv1alpha1.OperatorApplicationVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *operatorApplicationVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOperatorApplicationVersionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *operatorApplicationVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&applicationv1alpha1.OperatorApplicationVersion{}, f.defaultInformer)
}

func (f *operatorApplicationVersionInformer) Lister() v1alpha1.OperatorApplicationVersionLister {
	return v1alpha1.NewOperatorApplicationVersionLister(f.Informer().GetIndexer())
}
