apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-pg-cluster02
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      # delete cluster
      action: "update_cluster"
      clientVersion: "4.7.1"
      namespace: "pgtest"
      clusterName:
        - "test001"
      Selector: "name=test001"
      allFlag: false
      autofail: 1
      cpuLimit: "600m"
      cpuRequest: "600m"
      memoryLimit: "600Mi"
      memoryRequest: "600Mi"
      pvcSize: "10Gi"
      startup: true
      shutdown: false
      tolerations: []