apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: pg-test001
  namespace: pg-test
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: pg-test001
      namespace: pg-test
    spec:
      clientVersion: "4.7.1"
      name: "pg-test001"
      namespace: "pg-test"
      syncReplication: true
      ccpImage: ""
      ccpImageTag: ""
      pgVersion: "12"
      replicaCount: 1
      cpuLimit: "500m"
      cpuRequest: "500m"
      memoryLimit: "1Gi"
      memoryRequest: "1Gi"
      database: "db1"
      username: "pguser1"
      password: "pass1"
      rollingUpdate: true
      restart: false
      storageConfig: "csi-ssd-enterprise"
