apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-pg-cluster02
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      # delete cluster
      action: "scale_cluster"
      clientVersion: "4.7.1"
      namespace: "pgtest"
      name: "test001"
      ccpImageTag: ""
      nodeLabel: ""
      replicaCount: 2
      serviceType: ""
      storageConfig: ""
      tolerations: []

