apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: pg-cluster-xx0
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: pg-test-01
      namespace: pgtest
    spec:
      clientVersion: "4.7.1"
      name: "test001"
      namespace: "pgtest"
      syncReplication: true
      ccpImage: ""
      ccpImageTag: ""
      replicaCount: 1
      cpuLimit: "500m"
      cpuRequest: "500m"
      memoryLimit: "1Gi"
      memoryRequest: "1Gi"
      database: "db1"
      username: "pguser1"
      password: "pass1"