apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: pg-cluster-xx0
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      # create cluster
      action: "create_cluster"
      clientVersion: "4.7.1"
      name: "pg-cluster-xx0"
      namespace: "pgtest"
      syncReplication: true
      ccpImage: ""
      ccpImageTag: ""
      replicaCount: 2
      cpuLimit: "500m"
      cpuRequest: "500m"
      memoryLimit: "500Mi"
      memoryRequest: "500Mi"
      database: "db1"
      username: "pguser1"
      password: "pass1"
