apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: test001
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      clientVersion: "4.7.1"
      name: "test001"
      namespace: "pgtest"

