apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-pg-cluster02
  namespace: pgtest
spec:
  kind: "PostgreSQL"
  appVersion: "12.0"
  version: 1
  customResource: |
    apiVersion: pgcluster.kubesphere.io/v1alpha1
    kind: PostgreSQLCluster
    metadata:
      name: postgresqlcluster-sample
    spec:
      name: "test001"
      namespace: "pgtest"
      cpuLimit: "600m"
      cpuRequest: "600m"
      memoryLimit: "600Mi"
      memoryRequest: "600Mi"
      pvcSize: "10Gi"

