apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-xxx
  namespace: mysql-test
spec:
  kind: "ClickHouse"
  appVersion: "20.9"
  version: 2
  customResource: |
      apiVersion: "clickhouse.radondb.com/v1"
      kind: "ClickHouseInstallation"
      metadata:
        name: ck-cluster
        namespace: ck-project
      spec:
        configuration:
          # Zookeeper 配置。需要根据 Zookeeper 配置来正确填写。属于创建 ClickHouse Cluster 时的必填字段。
          # 在 ClickHouse 项目 https://github.com/radondb/radondb-clickhouse-kubernetes 中，
          # nodes 数量由 https://github.com/radondb/radondb-clickhouse-kubernetes/blob/main/clickhouse-cluster/values.yaml#L43 决定。
          zookeeper:
            nodes:
              - host: zookeeper-0.zookeeper-server.ck-project
                port: 2181
              - host: zookeeper-1.zookeeper-server.ck-project
                port: 2181
              - host: zookeeper-2.zookeeper-server.ck-project
                port: 2181
          users:
            # ClickHouse User profile 配置。不希望展示。
            readonly/profile: readonly
            # clickhouse/password 代表 ClickHouse 数据库帐号 clickhouse 的密码为 c1ickh0use0perator
            clickhouse/password: c1ickh0use0perator
            # clickhouse/networks/ip 代表 ClickHouse 数据库帐号 clickhouse 的可允许访问的网络为 127.0.0.1 和 ::/0
            clickhouse/networks/ip:
              - 127.0.0.1
              - ::/0
            # ClickHouse 数据库用户 clickhouse 的 profile 配置。希望可以进行修改，比如改成 readonly/profile 的值。
            # 不希望主动展示。
            clickhouse/profile: default
            # ClickHouse 数据库用户 clickhouse 的 quotas 配置。希望可以进行修改，不希望主动展示。
            clickhouse/quotas: default
          profiles:
            readonly/readonly: "1"
            default/max_memory_usage: "1024000000"
          quotas:
            default/interval/duration: "3600"
          settings:
            compression/case/method: zstd
            disable_internal_dns_cache: 1
          clusters:
            # 默认集群名称。创建后不可以修改。不希望展示。
            - name: all-nodes
              # Templates are specified for this cluster explicitly
              #        templates:
              #          podTemplate: pod-template-with-volume
              layout:
                # ClickHouse 分片数量，只支持增加，不支持减少。
                # shards count can not scale in this value.
                shardsCount: 3
                # ClickHouse 每个分片的副本数量，只支持在创建时进行修改。
                # 要求创建后，不允许再改动该值。
                # 同时希望前端可以限制该值在 1-3 之间配置。
                # replicas count can not modify this value when the cluster has already created.
                replicasCount: 2

        defaults:
          templates:
            podTemplate: pod-template-with-volume
            dataVolumeClaimTemplate: data
            logVolumeClaimTemplate: data
            serviceTemplate: chi-svc-template

        templates:
          serviceTemplates:
            - name: chi-svc-template
              spec:
                ports:
                  # HTTP 端口。创建后不希望修改。
                  # Port for HTTP/REST interface, see https://clickhouse.tech/docs/en/interfaces/http/
                  - name: http
                    port: 8123
                  # TCP 端口。不希望展示。
                  # Port for the native interface, see https://clickhouse.tech/docs/en/interfaces/tcp/
                  - name: tcp
                    port: 9000
                # ClickHouse 访问方式
                # servicee, value: ClusterIP/NodePort/LoadBalancer
                # see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
                type: NodePort
