apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-mysql
  namespace: mysql-test
spec:
  cluster: "host"
  kind: "MysqlCluster"
  appVersion: "5.7"
  version: 2
  customResource: |
      apiVersion: mysql.radondb.com/v1alpha1
      kind: Cluster
      metadata:
        name: sample
        namespace: mysql-project
      spec:
        replicas: 2
        mysqlVersion: "5.7"

        mysqlOpts:
          rootPassword: ""
          rootHost: localhost
          user: radondb_usr
          password: RadonDB@123
          database: randondb
          initTokuDB: true

          # A simple map between string and string.
          # Such as:
          #    mysqlConf:
          #      expire_logs_days: "7"
          mysqlConf: {}

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

        xenonOpts:
          image: radondb/xenon:1.1.5-alpha
          admitDefeatHearbeatCount: 5
          electionTimeout: 10000

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi

        metricsOpts:
          enabled: false
          image: prom/mysqld-exporter:v0.12.1

          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

        podSpec:
          imagePullPolicy: IfNotPresent
          sidecarImage: radondb/mysql-sidecar:latest
          busyboxImage: busybox:1.32

          slowLogTail: false
          auditLogTail: false

          labels: {}
          annotations: {}
          affinity: {}
          priorityClassName: ""
          tolerations: []
          schedulerName: ""

          resources:
            requests:
              cpu: 10m
              memory: 32Mi

        persistence:
          enabled: true
          accessModes:
          - ReadWriteOnce
          #storageClass: ""
          size: 10Gi