apiVersion: application.kubesphere.io/v1alpha1
kind: Manifest
metadata:
  name: manifest-xxx
  namespace: mysql-test
spec:
  kind: "ClickHouse"
  appVersion: "20.9"
  version: 2
  customResource: |
      apiVersion: "clickhouse.radondb.com/v1"
      kind: "ClickHouseInstallation"
      metadata:
        name: ck-cluster
        namespace: ck-project
      spec:
        configuration:
          # Zookeeper 配置。需要根据 Zookeeper 配置来正确填写。属于创建 ClickHouse Cluster 时的必填字段。
          # 在 ClickHouse 项目 https://github.com/radondb/radondb-clickhouse-kubernetes 中，
          # nodes 数量由 https://github.com/radondb/radondb-clickhouse-kubernetes/blob/main/clickhouse-cluster/values.yaml#L43 决定。
  relatedResources:
    - name: xx
      data: |
        xxx
    - name: xx
      data: |
        xxx