apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplicationVersion
metadata:
  name: clickhouse
  labels:
    category_id: radondb
spec:
  name: "RadonDB ClickHouse"
  screenshots: |
    /assets/screenshots/radondb_list.jpg,/assets/screenshots/ck_create.jpg,/assets/screenshots/ck_detail.jpg,/assets/screenshots/ck_monitor.jpg
  screenshots_zh: |
    /assets/screenshots/radondb_list_zh.jpg,/assets/screenshots/ck_create_zh.jpg,/assets/screenshots/ck_detail_zh.jpg,/assets/screenshots/ck_monitor_zh.jpg
  changeLog: |
    - Support ClickHouse kernel version 21.1.3.32
    - Rich display of monitoring metrics
    - Support horizontal and vertical expansion
    - SVC-based cluster load balancing
    - High-availability based on multiple replicas
    - Fine-grained cluster state presentation
    - Disk expansion support qingcloud-csi
    - Compatible kubernetes api extension version v1
    - Automatically create/delete/configure ZooKeeper cluster dependencies
  changeLog_zh: |
    - 支持 21.1.3.32 内核版本
    - 丰富的监控指标展示
    - 支持集群水平垂直扩容
    - 基于 SVC 的集群负载均衡
    - 基于多副本的高可用功能
    - 提供了细粒度的集群状态展示
    - 磁盘扩容兼容了 qingcloud-csi
    - 兼容了 kubernetes api extension v1 版本
    - 支持自动创建 / 删除 / 配置 ZooKeeper 集群依赖
  operatorVersion: "2.1.0"
  appVersion: "21.1.3.32"
  owner: "RadonDB"
status:
  state: active
