apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: mysql
spec:
  # app name
  name: "MySQL"
  # app description
  description: "基于 MySQL 提供的企业级数据库服务，支持一主多从高可用架构，支持自动备份、监控告警、弹性伸缩、参数管理等数据库生命周期运维管理功能。"
  # app description
  abstraction: |
    - 金融级高可靠的 MySQL 集群；
    - 主从开启 Semi-sync，严格保证节点间的数据一致性；
    - 集群为一主多从架构，使用 Raft 协议管理集群主从节点，故障时可实现秒级主从切换，保障业务连续性；
    - 提供自动备份、监控告警等功能；
  operator: "admin"
  icon: "https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/docs/images/logo_radondb-mysql.png"
  owner: "RadonDB"
status:
  state: active
