apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: mysql
spec:
  # app name
  name: "MySQL"
  # app description
  description: "mysql 是最流行的开源数据库，应用广泛，性能稳定。"
  # app description
  abstraction: |
    - 介绍这个是mysql介绍
    - mysql介绍
    - mysql介绍
    - test text
  operator: "admin"
  icon: "https://raw.githubusercontent.com/radondb/radondb-mysql-kubernetes/main/docs/images/logo_radondb-mysql.png"
  owner: "RadonDB"
status:
  state: active
