apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/vendor: kubesphere
    app: clickhouse-operator
spec:
  selector:
    matchLabels:
      app: clickhouse-operator
  endpoints:
    - path: /metrics
      port: clickhouse-operator-metrics
