apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/vendor: kubesphere
    app: clickhouse-operator
spec:
  selector:
    matchLabels:
      app: clickhouse-operator
  endpoints:
    - path: /metrics
      port: clickhouse-operator-metrics

app.kubernetes.io/component: database
app.kubernetes.io/instance: mysql-vcl69s
app.kubernetes.io/managed-by: mysql.radondb.com
app.kubernetes.io/name: mysql
app.kubernetes.io/version: 5.7.34
controller-revision-hash: mysql-vcl69s-mysql-59b885667
healthy: "no"
mysql.radondb.com/cluster: mysql-vcl69s
role: leader
statefulset.kubernetes.io/pod-name: mysql-vcl69s-mysql-0